#nullable enable
using System;
using System.Linq;
using System.Text;

namespace Firebug.Cli
{
    /// <summary>
    /// Emits shell tab-completion scripts generated from <see cref="CommandCatalog"/>
    /// at runtime — completion cannot drift from the CLI because both read the
    /// same table. PowerShell only in v1 (named explicitly so bash/zsh variants
    /// can be added without grammar changes). Activation is one profile line:
    ///
    ///   firebug completion powershell | Out-String | Invoke-Expression
    ///
    /// The emitted script is side-effect-free beyond registering the completer,
    /// never throws in constrained sessions (outer try/catch to Write-Verbose),
    /// and is never required for the tool to function.
    /// </summary>
    public static class CompletionEmitter
    {
        public static string EmitPowerShell()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# firebug tab-completion for PowerShell.");
            sb.AppendLine("# Generated by 'firebug completion powershell' from the CLI's own command");
            sb.AppendLine("# catalog - regenerate after upgrading firebug. Activation (profile line):");
            sb.AppendLine("#   firebug completion powershell | Out-String | Invoke-Expression");
            sb.AppendLine("try {");
            sb.AppendLine("  Register-ArgumentCompleter -Native -CommandName firebug -ScriptBlock {");
            sb.AppendLine("    param($wordToComplete, $commandAst, $cursorPosition)");
            sb.AppendLine("    $catalog = @{");
            foreach (var c in CommandCatalog.Commands.OrderBy(c => c.Name, StringComparer.Ordinal))
            {
                var flags = c.Flags
                    .SelectMany(f => f.Short == null ? new[] { f.Long } : new[] { f.Long, f.Short })
                    .Distinct()
                    .OrderBy(n => n, StringComparer.Ordinal)
                    .Select(n => "'" + n + "'");
                sb.AppendLine($"      '{c.Name}' = @({string.Join(", ", flags)})");
            }
            sb.AppendLine("    }");
            sb.AppendLine("    try {");
            sb.AppendLine("      $elems = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })");
            sb.AppendLine("      # $elems[0] is the program itself. The verb is settled once a second");
            sb.AppendLine("      # element exists that is NOT the token being completed.");
            sb.AppendLine("      $verb = if ($elems.Count -ge 2 -and $elems[1] -ne $wordToComplete) { $elems[1] } else { $null }");
            sb.AppendLine("      $pool = if ($null -eq $verb) { $catalog.Keys } else { $catalog[$verb] }");
            sb.AppendLine("      if ($null -eq $pool) { $pool = @() }");
            sb.AppendLine("      $pool | Where-Object { $_ -like \"$wordToComplete*\" } | Sort-Object | ForEach-Object {");
            sb.AppendLine("        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)");
            sb.AppendLine("      }");
            sb.AppendLine("    } catch { }");
            sb.AppendLine("  }");
            sb.AppendLine("} catch { Write-Verbose 'firebug: completion registration failed (constrained session?)' }");
            return sb.ToString();
        }
    }
}
